### ISSUE TITLE
Sone does not save after restarting

### ISSUE THREAD

**Issue by porky11** [Bombe/Sone#14]
I use the version of freenet on arch linux from the aur.
Everything works as expected, even my Sone identity does not get deleted, but all my posts are gone after restarting freenet, my uploaded images, my saved options (automatically follow, don't show message for new sones, etc.), and the sones I already followes, are deleted, so I have to follow them again

**Comment by Bombe** [comment]
Unfortunately I have never been able to replicate this behaviour. It would be good if you could confirm that this happens on a current version of Freenet that has been installed from [the website](https://freenetproject.org/) or from source code.

**Comment by Bombe** [comment]
I might have recently discovered the source of this issue and am currently testing a fix.

**Comment by Bombe** [comment]
The fix will be a part of the next version, v81.
