### ISSUE TITLE
'Custom fields' shows wrong data after entry

### ISSUE THREAD

**Issue by dosadi** [Bombe/Sone#18]
When I create a field called 'Freemail address' and enter a freemail address into the data field, when I go to the profile page to look at it, I see 'username@username.freemail' instead of the complete freemail address.  The incorrect address is a link whose link location is the correct freemail address, but the text of the link is incorrect.

**Comment by Bombe** [comment]
Well, the text is not what you entered, that’s correct but that is intended. Sone tries to represent certain elements in a way that’s better understandable. The full Freemail address is just a bunch of mumbo-jumbo but the displayed text links it more clearly to an identity. And the link will take you to the correct page in the Freemail plugin.

**Comment by dosadi** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  Ok, is there a way to turn that behavior off?  I'd like people to be able to cut and paste the address into their address book, etc.  What logic triggers the behavior?  If I knew that, I might be able to work around it with some small renaming or something....Jon                                                                                                                                             Sent via BlackBerry Hub+ Inbox for Android                                                                                                                                                                           From: notifications@github.comSent: July 20, 2019 10:43 AMTo: Sone@noreply.github.comReply-to: reply@reply.github.comCc: dosadi82@gmail.com; author@noreply.github.comSubject: Re: [Bombe/Sone] 'Custom fields' shows wrong data after entry (#18)  Well, the text is not what you entered, that’s correct but that is intended. Sone tries to represent certain elements in a way that’s better understandable. The full Freemail address is just a bunch of mumbo-jumbo but the displayed text links it more clearly to an identity. And the link will take you to the correct page in the Freemail plugin.

**Comment by Bombe** [comment]
It it’s a valid freemail address it’s going to be formatted in the afore-mentioned way and there are currently no plans to change this…
