### ISSUE TITLE
Not recognizing available identities

### ISSUE THREAD

**Issue by chris-ch** [Bombe/Sone#19]
I am new to Freenet so maybe doing something wrong, but it looks suspicious. I get the following message on Sone after having installed the WebOfTrust plugin and created some identities with several trusters already:
"You do not have any Web of Trust identities. Please head over to the Web of Trust plugin and create an identity."

It had worked at some point and I was able to create Sones, but suddenly Web of Trust was not recognized. Re-installing Sone did not help. I am using the latest v82 version with WebOfTrust 0.4.5 build0020

**Comment by Bombe** [comment]
The communication between WoT and Sone is not instant. Sometimes one plugin or the other needs a kick in the teeth make it all work together. However, at least after a restart of the node Sone should successfully recognize all your local WoT identities, and it will let you login with those that you already created a Sone for and offers you to create a Sone for those for which you haven’t done that yet.
